/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KlixLoader {
        "isVisible": boolean;
    }
    interface KlixPayLater {
        "amount": string;
        "brandId": string;
        "language": string;
    }
}
declare global {
    interface HTMLKlixLoaderElement extends Components.KlixLoader, HTMLStencilElement {
    }
    var HTMLKlixLoaderElement: {
        prototype: HTMLKlixLoaderElement;
        new (): HTMLKlixLoaderElement;
    };
    interface HTMLKlixPayLaterElement extends Components.KlixPayLater, HTMLStencilElement {
    }
    var HTMLKlixPayLaterElement: {
        prototype: HTMLKlixPayLaterElement;
        new (): HTMLKlixPayLaterElement;
    };
    interface HTMLElementTagNameMap {
        "klix-loader": HTMLKlixLoaderElement;
        "klix-pay-later": HTMLKlixPayLaterElement;
    }
}
declare namespace LocalJSX {
    interface KlixLoader {
        "isVisible"?: boolean;
    }
    interface KlixPayLater {
        "amount"?: string;
        "brandId"?: string;
        "language"?: string;
    }
    interface IntrinsicElements {
        "klix-loader": KlixLoader;
        "klix-pay-later": KlixPayLater;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "klix-loader": LocalJSX.KlixLoader & JSXBase.HTMLAttributes<HTMLKlixLoaderElement>;
            "klix-pay-later": LocalJSX.KlixPayLater & JSXBase.HTMLAttributes<HTMLKlixPayLaterElement>;
        }
    }
}
