version: "3.8"
services:
  demo:
    image: node:18
    volumes:
      - ./klix-demo:/app
    working_dir: /app
    ports:
      - 5173:5173
    command: sh -c "npm install && npm run host"
    depends_on:
      - widget

  widget:
    image: node:18
    volumes:
      - ./klix-widget:/app
    working_dir: /app
    ports:
      - 8888:8888
    command: sh -c "npm install && npm run start"